import type { BonusApplication, BonusCategory, StudentProfile, SystemSettings } from './types'

export const mockStudents: StudentProfile[] = [
  {
    id: 'stu-1',
    name: '张三',
    studentId: '2021001',
    department: '第一项目组',
    major: '运营支持',
    grade: 'A批次',
    academicScore: 93,
    moralScore: 94,
    practiceScore: 88,
    sportsScore: 82,
    failedCourses: 0,
    hasPunishment: false,
    volunteerHours: 120,
    accountStatus: 'inactive',
    password: '123456',
    mustChangePassword: true,
  },
  {
    id: 'stu-2',
    name: '李四',
    studentId: '2021002',
    department: '第一项目组',
    major: '技术支持',
    grade: 'A批次',
    academicScore: 89,
    moralScore: 91,
    practiceScore: 92,
    sportsScore: 85,
    failedCourses: 0,
    hasPunishment: false,
    volunteerHours: 86,
    accountStatus: 'active',
    password: '123456',
    mustChangePassword: false,
    activatedAt: '2026-07-18T09:00:00.000Z',
    lastLoginAt: '2026-07-24T10:12:00.000Z',
  },
  {
    id: 'stu-3',
    name: '王五',
    studentId: '2021003',
    department: '第二项目组',
    major: '数据分析',
    grade: 'A批次',
    academicScore: 91,
    moralScore: 92,
    practiceScore: 76,
    sportsScore: 90,
    failedCourses: 1,
    hasPunishment: false,
    volunteerHours: 64,
    accountStatus: 'active',
    password: '123456',
    mustChangePassword: false,
    activatedAt: '2026-07-18T10:15:00.000Z',
    lastLoginAt: '2026-07-19T08:20:00.000Z',
  },
  {
    id: 'stu-4',
    name: '赵六',
    studentId: '2021004',
    department: '第一项目组',
    major: '运营支持',
    grade: 'A批次',
    academicScore: 84,
    moralScore: 85,
    practiceScore: 90,
    sportsScore: 78,
    failedCourses: 0,
    hasPunishment: true,
    volunteerHours: 100,
    accountStatus: 'inactive',
    password: '123456',
    mustChangePassword: true,
  },
  {
    id: 'stu-5',
    name: '钱七',
    studentId: '2022001',
    department: '第二项目组',
    major: '智能应用',
    grade: 'B批次',
    academicScore: 96,
    moralScore: 98,
    practiceScore: 95,
    sportsScore: 88,
    failedCourses: 0,
    hasPunishment: false,
    volunteerHours: 150,
    accountStatus: 'active',
    password: '123456',
    mustChangePassword: false,
    activatedAt: '2026-07-20T14:00:00.000Z',
    lastLoginAt: '2026-07-22T11:04:00.000Z',
  },
  {
    id: 'stu-6',
    name: '孙八',
    studentId: '2022002',
    department: '第二项目组',
    major: '数据分析',
    grade: 'B批次',
    academicScore: 83,
    moralScore: 88,
    practiceScore: 82,
    sportsScore: 75,
    failedCourses: 0,
    hasPunishment: false,
    volunteerHours: 45,
    accountStatus: 'locked',
    password: '123456',
    mustChangePassword: true,
  },
]

export const mockCategories: BonusCategory[] = [
  {
    id: 'cat-competition',
    name: '竞赛与评比成果',
    defaultScore: 6,
    maxScore: 10,
    description: '竞赛、评比、评选活动中取得的成果证明。',
    active: true,
  },
  {
    id: 'cat-research',
    name: '项目与成果证明',
    defaultScore: 8,
    maxScore: 12,
    description: '项目结项、成果发布、专利软著等证明材料。',
    active: true,
  },
  {
    id: 'cat-volunteer',
    name: '服务与贡献记录',
    defaultScore: 3,
    maxScore: 6,
    description: '服务时长、活动贡献、协作支持等证明材料。',
    active: true,
  },
  {
    id: 'cat-honor',
    name: '荣誉与表彰',
    defaultScore: 4,
    maxScore: 8,
    description: '个人荣誉、团队表彰、优秀成员等证明。',
    active: true,
  },
]

export const mockApplications: BonusApplication[] = [
  {
    id: 'app-1',
    applicationNo: 'SQ-2026-0001',
    studentId: '2021001',
    categoryId: 'cat-competition',
    title: '年度技能评比二等奖',
    description: '参加年度技能评比，获得二等奖。',
    requestedScore: 6,
    approvedScore: 6,
    status: 'approved',
    attachments: [],
    reviewLogs: [
      {
        id: 'log-app-1-submit',
        action: 'submitted',
        actorName: '张三',
        comment: '提交申报材料',
        score: 6,
        createdAt: '2026-07-20T09:30:00.000Z',
      },
      {
        id: 'log-app-1-review',
        action: 'approved',
        actorName: '管理员',
        comment: '证书信息完整，按规则认定。',
        score: 6,
        createdAt: '2026-07-21T15:10:00.000Z',
      },
    ],
    submittedAt: '2026-07-20T09:30:00.000Z',
    reviewedAt: '2026-07-21T15:10:00.000Z',
    reviewerName: '管理员',
    reviewComment: '证书信息完整，按规则认定。',
  },
  {
    id: 'app-2',
    applicationNo: 'SQ-2026-0002',
    studentId: '2022001',
    categoryId: 'cat-research',
    title: '重点项目结项优秀',
    description: '参与重点项目并完成结项，验收结果优秀。',
    requestedScore: 8,
    approvedScore: 8,
    status: 'approved',
    attachments: [],
    reviewLogs: [
      {
        id: 'log-app-2-submit',
        action: 'submitted',
        actorName: '钱七',
        comment: '提交申报材料',
        score: 8,
        createdAt: '2026-07-22T11:00:00.000Z',
      },
      {
        id: 'log-app-2-review',
        action: 'approved',
        actorName: '管理员',
        comment: '材料有效。',
        score: 8,
        createdAt: '2026-07-23T10:20:00.000Z',
      },
    ],
    submittedAt: '2026-07-22T11:00:00.000Z',
    reviewedAt: '2026-07-23T10:20:00.000Z',
    reviewerName: '管理员',
    reviewComment: '材料有效。',
  },
  {
    id: 'app-3',
    applicationNo: 'SQ-2026-0003',
    studentId: '2021002',
    categoryId: 'cat-volunteer',
    title: '专项服务支持',
    description: '累计参与专项服务支持 42 小时。',
    requestedScore: 3,
    approvedScore: 0,
    status: 'pending',
    attachments: [],
    reviewLogs: [
      {
        id: 'log-app-3-submit',
        action: 'submitted',
        actorName: '李四',
        comment: '提交申报材料',
        score: 3,
        createdAt: '2026-07-24T13:45:00.000Z',
      },
    ],
    submittedAt: '2026-07-24T13:45:00.000Z',
  },
  {
    id: 'app-4',
    applicationNo: 'SQ-2026-0004',
    studentId: '2021003',
    categoryId: 'cat-honor',
    title: '优秀成员表彰',
    description: '2025-2026 评分周期优秀成员。',
    requestedScore: 4,
    approvedScore: 0,
    status: 'rejected',
    attachments: [],
    reviewLogs: [
      {
        id: 'log-app-4-submit',
        action: 'submitted',
        actorName: '王五',
        comment: '提交申报材料',
        score: 4,
        createdAt: '2026-07-19T08:15:00.000Z',
      },
      {
        id: 'log-app-4-review',
        action: 'rejected',
        actorName: '管理员',
        comment: '证明材料缺少盖章页，请补充后重新提交。',
        score: 0,
        createdAt: '2026-07-20T16:30:00.000Z',
      },
    ],
    submittedAt: '2026-07-19T08:15:00.000Z',
    reviewedAt: '2026-07-20T16:30:00.000Z',
    reviewerName: '管理员',
    reviewComment: '证明材料缺少盖章页，请补充后重新提交。',
  },
]

export const mockSettings: SystemSettings = {
  academicYear: '2025-2026 评分周期',
  submissionDeadline: '2026-08-31',
  weights: {
    academic: 60,
    moral: 15,
    practice: 15,
    sports: 10,
    bonusCap: 20,
  },
}

export const departments = ['第一项目组', '第二项目组', '第三项目组']
export const grades = ['A批次', 'B批次', 'C批次', 'D批次']
